image: "ruby:2.4.4"

services :
  - postgres:latest

variables :
  POSTGRES_DB: Citrakara_development

cache :
  paths:
    - vendor/ruby

stages :
  - build
  - deploy

proses compile:
  variables :
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  stage: build
  script:
  - apt-get update && apt install -y -qq nodejs
  - gem install bundler --no-ri --no-rdoc
  - gem install execjs
  - RAILS_ENV=test bundle install --jobs $(nproc) "${FLAGS[@]}"
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  except :
  - master

proses deploy production :
  stage: deploy
  environment: production
  script:
  - gem install dpl
  - dpl --provider=heroku --app=test-heroku-12 --api-key=129d9e0d-6947-4243-abc8-33694585bcce
  only :
  - master